language: php
php:
- '5.6'
services:
- mysql
before_script:
- git clone https://github.com/shopware/shopware.git /tmp/shopware
- cd ..
- cd /tmp/shopware
- ant -f build/build.xml -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
- cp -R /home/travis/build/PAYONE-GmbH/shopware-5/Frontend/MoptPaymentPayone /tmp/shopware/engine/Shopware/Plugins/Default/Frontend
- cd /tmp/shopware
- ls engine/Shopware/Plugins/Default/Frontend
- php bin/console sw:plugin:refresh
- php bin/console sw:plugin:list
- php bin/console sw:plugin:install MoptPaymentPayone
- php bin/console sw:plugin:activate MoptPaymentPayone
- php bin/console sw:generate:attributes
- php bin/console orm:generate:proxies
- cd /tmp/shopware/tests
script:
- cd $TRAVIS_BUILD_DIR
- ant
before_deploy:
- export PACKAGE=$(ls *.zip)
- echo "Deploying $PACKAGE"
deploy:
  provider: releases
  api_key:
    secure: APIF9F9Id8DqG0APwdFK3gG4Cn+TXhEaDpfTGFbQ/aEaRkZ39OnJVNGhTtS9QK+7lc1HMbZnMOT4YYTCL/Hk8dkqeGJ5aiZaxGrmD9lJTKNaeGHRe8oJM/lGhR07xX5IUfUPlGW1O2Mj4VFR+lfbJk8cyPSov21TANZUSYdBlHsDGPTPaJRdcca6VBM4kD9dBGq4kwUA6/IGi4c/hPIsK9KXP7kdY65ht0mdQsolqQtGOGWlCN4iOZB3KqeBxJ7pJ+QECKouk0jhDl5agl+PWqBEqHj+sdSUO61jXsF3GfaQDb3CILN4FL2ZXwMMGMWgWfuAl12+KFRL2TUDB0pcO7bbTyTOAxlWLUjb7AU3R0HTqCzzD5b29GOdcp4/0OeiT+GD3qeAJkCnWX7ZgwrXVXrq7FNj2K92WtzK4vKsg9TLPRDzBgWWiwIZxEFaE6e7TnnK27hpzcoQZecL4oS4aamA7Yj4A0M3OKUFo6xz0J0FeMZNMXBZZa4YX31WKtcKhdlaGn+RgGzcnvbQRXcTB8dVihoaHUAhRhpzJvYU3CHMaVOPhreEAew/f2vs2Q641yyNNBgJq3M98XAKCzT5KzCYLhnfVkd3Xwx3BgnAM3P2wYesLcsQxrh3g4nHRyuY+D8yYh1/scQLmc2talxnTv3rv7HSnljwDqH5bFYbIXc=
  file:
  - "${PACKAGE}"
  on:
    repo: PAYONE-GmbH/shopware-5
    all_branches: true
    tags: true
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: BnPN3t23S+44tENFvtUJAFTYGMJcHmG973s5+xBlKvSRg59PTo6b7pgR6bbLt8hNT1FxocxbmVRkVbxX41JVNmQ6q6ezpcunMWTnikhVSx1suM7Y1Q35LNBcNgBqxrcGyGE3mmyVfYa2Siyy8HVmoNPXx/v5l2vn8pM4JnEQ0w45S/bwy1/rlsI4g0tQ8Rh1r/DR4TJUa/mCTQP0p4Vi0+L5b9vO3OCctwMqYSGA9E6Hgv+m8KMJcFut6FrcIw67lPmVbWhpl9j5HrxeXLAq5pLpPcBfR9QQTXzQshd4+ygqtzpxm444CHlIrvmdrtRFoGjDv3MVPTKKRp/vyrn/GxWziIHzV4u7vfUbCBHMYxGkuZZPxDCuDexuiLoyVo4vAKyRhBsUrse9EhYr1eVAFPkDa1VgUgwwjDv9HS012ipyFGK2FbL/Z0qi+d6/FONLOUFSI5vAVmVug4QtBiqdeN9glqzgknkEcn/5yZi0RBfehy7Zuo95HAW3J7b3e0kFbRG9duKxd9OlPhNQQOU1mLTPNDyfx7jC321247v0GBEra7Cw4FQB1mKG2BXxchz+yTny0tnHGBNqd9P/rv+op8LC5lfruiI4g5An7ykCdlN0BIHVHIuK5Cg4h8Vb44gO3dzEuU0nYX3WCXZOCIUCz9njjqXKFYbc9+FIiVusG0Y=
