language: php
php:
- '5.6'
services:
- mysql
before_script:
- git clone https://github.com/shopware/shopware.git /tmp/shopware
- cd ..
- cd /tmp/shopware
- ant -f build/build.xml -Ddb.user=travis -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
- cp -R /home/travis/build/fjbender/shopware-5/Frontend/MoptPaymentPayone /tmp/shopware/engine/Shopware/Plugins/Default/Frontend
- cd /tmp/shopware
- ls engine/Shopware/Plugins/Default/Frontend
- php bin/console sw:plugin:refresh
- php bin/console sw:plugin:list
- php bin/console sw:plugin:install MoptPaymentPayone
- php bin/console sw:plugin:activate MoptPaymentPayone
- php bin/console sw:generate:attributes
- php bin/console orm:generate:proxies
- cd /tmp/shopware/tests
script:
- cd $TRAVIS_BUILD_DIR
- ant
before_deploy:
- export PACKAGE=$(ls *.zip)
- echo "Deploying $PACKAGE"
deploy:
  provider: releases
  api_key:
    secure: APIF9F9Id8DqG0APwdFK3gG4Cn+TXhEaDpfTGFbQ/aEaRkZ39OnJVNGhTtS9QK+7lc1HMbZnMOT4YYTCL/Hk8dkqeGJ5aiZaxGrmD9lJTKNaeGHRe8oJM/lGhR07xX5IUfUPlGW1O2Mj4VFR+lfbJk8cyPSov21TANZUSYdBlHsDGPTPaJRdcca6VBM4kD9dBGq4kwUA6/IGi4c/hPIsK9KXP7kdY65ht0mdQsolqQtGOGWlCN4iOZB3KqeBxJ7pJ+QECKouk0jhDl5agl+PWqBEqHj+sdSUO61jXsF3GfaQDb3CILN4FL2ZXwMMGMWgWfuAl12+KFRL2TUDB0pcO7bbTyTOAxlWLUjb7AU3R0HTqCzzD5b29GOdcp4/0OeiT+GD3qeAJkCnWX7ZgwrXVXrq7FNj2K92WtzK4vKsg9TLPRDzBgWWiwIZxEFaE6e7TnnK27hpzcoQZecL4oS4aamA7Yj4A0M3OKUFo6xz0J0FeMZNMXBZZa4YX31WKtcKhdlaGn+RgGzcnvbQRXcTB8dVihoaHUAhRhpzJvYU3CHMaVOPhreEAew/f2vs2Q641yyNNBgJq3M98XAKCzT5KzCYLhnfVkd3Xwx3BgnAM3P2wYesLcsQxrh3g4nHRyuY+D8yYh1/scQLmc2talxnTv3rv7HSnljwDqH5bFYbIXc=
  file:
    - "${PACKAGE}"
  on:
    repo: PAYONE-GmbH/shopware-5
    all_branches: true
    tags: true
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: e+EIyCPTEEbpBU34zbU5cSFH5zOMkHkgQxGVq4QT47CQl8ooiWTaXjrUpIivaGG5bpT7gxMKkcGuZUdDzJ3SzS8zGKERMDgjnuSL84NzYq13CRr9yvYOg+xOxVLvqGC5eMJQWs4l2U8G7Q6SaqEuP9IT5eQ+UxrNqfx0uhag/ylknvTwopyg7TajPQ2v9zKeXXtshet40Du0vSG0+rJ4G/iZD+xAyTl8kp+O2TcfU0PeYqnceY7+beayj5HbD5cN31LGFdLCMcRXp7HgwPoOA9XsdGsCEq2NgrlDSgirg17R1wukdvlPljiLekX3xDwHLX6x9NZ8b5rECgJlLFlDWXW+dbf9iFBLTUVJSiUumDk4dRYmA6WPvm/olKN3EEjs6cDc7V/V2XfJqeGkQmv4vLMPjnuk+oygl9kmlCtmK0EyWvxw25HaijYxWyPITp9DQ+3b137AeLcToKbNlIFJjC1pmdi1C3oUjbjKu+NL8DMRG+z7F74o0cdqyNjKhYDmWmtYyIQFUml55wU5mG4WBlCGxAoKy14DpwfHlbPyZslB2A5CuqeJXZ0ewd5AqGBaZByTzFEJE4EUM7tbjG42B6wcK99FVoK6ffIIYOK/vliY6t/wQOK41JJNF5gYO7S3dFlJCEocX95J7Vipo9JV0MH+3isUECuyWZ/SvskMaTE=
